name: Docker image builds

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  docker-buildx:
    name: Debian build base
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dist: [buster]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker login
        run: |
          echo "${{ secrets.DOCKERHUB_USER }}" | \
            docker login --username "${{ secrets.DOCKERHUB_API_KEY }}" --password-stdin
      - name: Create buildx instance
        run: |
          docker run --rm --privileged docker/binfmt
          docker buildx create --use --name builder
          docker buildx inspect --bootstrap
      - name: Build image with buildx
        run: |
          docker buildx build \
            --platform linux/arm,linux/arm64,linux/amd64 \
            --push \
            --tag ${{ secrets.DOCKERHUB_USR }}/debian-${{ matrix.dist }}-buildbase \
            --file ./${{ matrix.dist }}.df .
