name: Docker image builds

# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  docker-buildx:
    name: Debian build base
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        dist: [buster]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_API_KEY }}
        run: |
          echo "${DOCKER_PASSWORD}" | \
            docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Create buildx instance
        run: |
          docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64
          docker buildx create --use --name builder
          docker buildx inspect --bootstrap
      - name: Build image with buildx
        env:
          THE_IMAGE: ${{ secrets.DOCKERHUB_USER }}/debian-${{ matrix.dist }}-buildbase
        run: |
          docker buildx build --platform linux/arm/v7 --push \
            --tag ${THE_IMAGE}:armv7 \
            --file ./${{ matrix.dist }}.df .
          docker buildx build --platform linux/arm64 --push \
            --tag ${THE_IMAGE}:armv64 \
            --file ./${{ matrix.dist }}.df .
          docker buildx build --platform linux/amd64 --push \
            --tag ${THE_IMAGE}:amd64 \
            --file ./${{ matrix.dist }}.df .
          docker manifest create ${THE_IMAGE}:latest \
            ${THE_IMAGE}:armv7 \
            ${THE_IMAGE}:arm64 \
            ${THE_IMAGE}:amd64
          docker manifest push ${THE_IMAGE}:latest
